name: Upload CSV to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-csv:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: mlops-project-428219

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage
        pip install pandas


     - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with: 
        project_id: '${{ env.PROJECT_ID }}'
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Run upload script
      env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: python src/upload_to_gcs.py
