name: Extract Data

on:
  schedule:
    - cron: '0 11 1 * *'  # Executa no primeiro dia de cada mês às 11:00 UTC (8:00 BRT)
  push:
    branches:
      - main
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  extract-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run extraction script
      run: python src/extract.py

    - name: Upload extraction status
      run: echo "Extraction successful" > extraction_status.txt
      if: ${{ success() }}
      continue-on-error: true

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: extraction-status
        path: extraction_status.txt
