name: Train Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite a execução manual do workflow

jobs:
  train-model:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: mlops-project-428219

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage pandas

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with: 
        project_id: '${{ env.PROJECT_ID }}'
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Run data process script
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: python src/process_data.py
